language: csharp
solution: Anakshiant.sln
mono: none
sudo: required
dist: xenial
dotnet: 2.2.502
script:
 - dotnet restore
 - dotnet test
global:
 - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
 - DOTNET_CLI_TELEMETRY_OPTOUT=1